// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  GALLERY_1: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw1fHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_10: "https://images.unsplash.com/photo-1667242196594-9f7229736796?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw3fHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_2: "https://images.unsplash.com/photo-1636019409518-7dd51dc8c31a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw4fHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_3: "https://images.unsplash.com/photo-1636019411146-354ed94f41be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw5fHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_4: "https://images.unsplash.com/photo-1667242197482-ffe672de74da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw2fHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_5: "https://images.unsplash.com/photo-1659391542239-9648f307c0b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxfHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_6: "https://images.unsplash.com/photo-1667207229735-266c430cca15?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwzfHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_7: "https://images.unsplash.com/photo-1667207229737-0adf3c700d5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwyfHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_8: "https://images.unsplash.com/photo-1667242196595-0f8f28afb92d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHwxMHx8bmFpbCUyMHBvbGlzaCUyMGJlYXV0eSUyMHNhbG9ufGVufDB8MHx8fDE3NzQ4NjA0Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
  GALLERY_9: "https://images.unsplash.com/photo-1667207229961-08f191f43543?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU2OTd8MHwxfHNlYXJjaHw0fHxuYWlsJTIwcG9saXNoJTIwYmVhdXR5JTIwc2Fsb258ZW58MHwwfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_1: "https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwyfHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_10: "https://images.unsplash.com/photo-1771441580033-3979bc33627b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwxfHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_2: "https://images.unsplash.com/photo-1633630555924-895b7b2d444c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw1fHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_3: "https://images.unsplash.com/photo-1642035271471-c2f7778908d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw0fHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_4: "https://images.unsplash.com/photo-1586973762963-9c610b87803d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw5fHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_5: "https://images.unsplash.com/photo-1644203541701-c67c866fd42a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwzfHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_6: "https://images.unsplash.com/photo-1661267571825-45b3036a1aed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw2fHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_7: "https://images.unsplash.com/photo-1743617206507-447c78118622?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw3fHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_8: "https://images.unsplash.com/photo-1698381731055-f81d76085dbd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw4fHxuYWlsJTIwYXJ0JTIwbWFuaWN1cmUlMjBjb2xvcmZ1bHxlbnwwfDF8fHwxNzc0ODYwNDc5fDA&ixlib=rb-4.1.0&q=80&w=1080",
  SERVICE_9: "https://images.unsplash.com/photo-1661267571820-eb5c6bd6634f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwxMHx8bmFpbCUyMGFydCUyMG1hbmljdXJlJTIwY29sb3JmdWx8ZW58MHwxfHx8MTc3NDg2MDQ3OXww&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
